### PR TITLE
feat(metrics): add labels for metrics in api-middleware

### PR DESCRIPTION
**Pull request by chrapek**
Hi, thanks for this library it helped me a lot.

One thing I was missing was more labels in some metrics in api-metrics.middleware. For now, I coded my own middleware however I think this can be useful for other people as well.

### CODE REVIEW

**Comment by pragmaticivan** [comment]
Hi, @chrapek Thanks for this PR! I actually had labels before but found that it actually increase cardinality by a lot. Did you find high increase of metrics in your observability stack? Perhaps you would want to leverage tracing for detailed signals like that?

**Comment by chrapek** [comment]
Oh, that is interesting. My first thought was that I didn't see any increasing cardinality. I will try to validate it today or during the weekend. 
I'm new to the metrics and the tracing world, so I'm not sure if I can use tracing in my use case as I just need some graphs in DataDog with a number of errors, etc.

**Comment by pragmaticivan** [comment]
@chrapek What are your thoughts on making those labels optional via the config option? With that I would be totally ok as long it defaults to no label. Otherwise, that would create a breaking change.

**Comment by pragmaticivan** [comment]
ping @chrapek

**Pull request closed without merging**
